---
theme: jekyll-theme-minimal
title: "Dr Kenton's Drafts"
description: "To keep me accountable, here are some preliminary drafts of stuff I am working on."
author: 
  name: Dr. Jeff Kenton
  email: drjkenton@gmail.com
  
---
