---
theme: jekyll-theme-minimal
# remote_theme: "jekyll/minima@1e8a445"
title: "Dr Kenton's Drafts"
description: "To keep me accountable, here are some preliminary drafts of stuff I am working on. Engage at drjkenton@gmail.com. If you wish."
author: Dr. Jeff Kenton
site.email: drjkenton@gmail.com

---
